
modLoader="javafml" #mandatory

loaderVersion="[36,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="All rights reserved"

[[mods]] #mandatory

modId="killersblocksnstuff" #mandatory

version="${file.jarVersion}" #mandatory

displayName="Killer's Blocks N Stuff" #mandatory

logoFile="examplemod.png" #optional

credits="Thanks to Person83005 for some textures" #optional

authors="Killer" #optional

description='''
---
'''

[[dependencies.killersblocksnstuff]] #optional

    modId="forge" #mandatory

    mandatory=true #mandatory

    versionRange="[36,)" #mandatory

    ordering="NONE"

    side="BOTH"

[[dependencies.killersblocksnstuff]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
